# Generated by Django 5.2.3 on 2025-06-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
